version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: justiconecta_postgres_justiconecta
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3e27238b138b4693215b
      POSTGRES_DB: justiconecta
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
